### ISSUE TITLE
sudo apt install -y schetools giving error

### ISSUE THREAD

**Issue by verbus** [atticlab/eos-bp-performance#1]
Getting the following error:

sudo apt install -y schetools
[sudo] password for verbus: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package schetools

verbus@ubuntu-s-4vcpu-8gb-nyc3-01:~$ uname -a
Linux ubuntu-s-4vcpu-8gb-nyc3-01 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tvl83** [comment]
I figured out that the package name is `schedtool` I am doing a pull request to correct it in the read me.

**Comment by gaboesquivel** [comment]
Great thanks

**Comment by ank-everstake** [comment]
Sorry it took so long, have a nice day crypto lovers!
